// <auto-generated />
namespace BeerTap.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOfficeIdKeg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOfficeIdKeg));
        
        string IMigrationMetadata.Id
        {
            get { return "201605300047250_AddOfficeIdKeg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
